# Generated by Django 3.0.3 on 2020-02-13 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaJugadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juegos_jugados', models.IntegerField(default=0)),
                ('juegos_titular', models.IntegerField(default=0)),
                ('goles', models.IntegerField(default=0)),
                ('autogoles', models.IntegerField(default=0)),
                ('minutos_jugados', models.IntegerField(default=0)),
                ('tarjetas_amarillas', models.IntegerField(default=0)),
                ('tarjetas_rojas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Jugadora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=256)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='fecha de nacimiento')),
                ('lugar_nacimiento', models.CharField(max_length=256)),
                ('estatura', models.FloatField()),
                ('peso', models.FloatField()),
                ('debut', models.FloatField()),
                ('posicion', models.CharField(max_length=1000)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviz.Club')),
            ],
        ),
    ]
