# Generated by Django 3.0.3 on 2020-02-21 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticajugadora',
            name='jugadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataviz.Jugadora'),
        ),
        migrations.AddField(
            model_name='jugadora',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
