# Generated by Django 3.0.3 on 2020-02-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0002_auto_20200221_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataviz.Club'),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='debut',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='estatura',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='nombre_completo',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jugadora',
            name='posicion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
