# Generated by Django 3.0.3 on 2020-02-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0003_auto_20200221_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
    ]
