# Generated by Django 3.0.3 on 2020-02-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0004_auto_20200221_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadora',
            name='liga_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
