# Generated by Django 3.0.3 on 2020-02-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0005_jugadora_liga_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadora',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
