# Generated by Django 3.0.3 on 2020-02-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0006_jugadora_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadora',
            name='debut',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
