# Generated by Django 3.0.3 on 2020-02-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0007_auto_20200226_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
