# Generated by Django 3.0.4 on 2020-03-18 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0010_auto_20200317_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticaHistoricaEquipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataviz.Torneo')),
            ],
        ),
    ]
