# Generated by Django 3.0.4 on 2020-03-18 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0011_estadisticahistoricaequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticahistoricaequipo',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dataviz.Club'),
        ),
    ]
