# Generated by Django 3.0.4 on 2020-03-18 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0012_estadisticahistoricaequipo_equipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='juego',
            old_name='goles_vistante',
            new_name='goles_visitante',
        ),
    ]
