# Generated by Django 3.0.4 on 2020-03-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0013_auto_20200318_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='fecha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
