# Generated by Django 3.0.4 on 2020-03-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0014_auto_20200318_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
