# Generated by Django 3.0.4 on 2020-03-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataviz', '0015_club_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='nombre_alternativo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
